export const products = [
  {
    name: 'Free Shirt',
    slug: 'free-shirt',
    category: 'Shirts',
    image:
      'https://raw.githubusercontent.com/basir/next-amazona/main/public/images/shirt1.jpg',
    isFeatured: true,
    featuredImage: './banner1.jpg',
    price: 70,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: 'A popular shirt',
  },
  {
    name: 'Fit Shirt',
    slug: 'fit-shirt',
    category: 'Shirts',
    image:
      'https://raw.githubusercontent.com/basir/next-amazona/main/public/images/shirt2.jpg',
    isFeatured: true,
    featuredImage: './banner2.jpg',
    price: 80,
    brand: 'Adidas',
    rating: 4.2,
    numReviews: 10,
    countInStock: 20,
    description: 'A popular shirt',
  },
  {
    name: 'Slim Shirt',
    slug: 'slim-shirt',
    category: 'Shirts',
    isFeatured: true,
    featuredImage: './banner3.jpg',
    image:
      'https://raw.githubusercontent.com/basir/next-amazona/main/public/images/shirt3.jpg',
    price: 90,
    brand: 'Raymond',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: 'A popular shirt',
  },
  {
    name: 'Golf Pants',
    slug: 'golf-pants',
    category: 'Pants',
    isFeatured: false,
    image:
      'https://raw.githubusercontent.com/basir/next-amazona/main/public/images/pants1.jpg',
    price: 90,
    brand: 'Oliver',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: 'Smart looking pants',
  },
  {
    name: 'Fit Pants',
    slug: 'fit-pants',
    category: 'Pants',
    isFeatured: false,
    image:
      'https://raw.githubusercontent.com/basir/next-amazona/main/public/images/pants2.jpg',
    price: 95,
    brand: 'Zara',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: 'A popular pants',
  },
  {
    name: 'Classic Pants',
    slug: 'classic-pants',
    category: 'Pants',
    isFeatured: false,
    image:
      'https://raw.githubusercontent.com/basir/next-amazona/main/public/images/pants3.jpg',
    price: 75,
    brand: 'Casely',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: 'A popular pants',
  },
];

export const users = [{ id: 1, username: 'fizzy', password: 'fizzy.com' }];
